# Generated by Django 3.0.6 on 2020-05-29 06:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oplm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oplm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OPLM',
                'verbose_name_plural': 'OPLMs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OplmMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('mediatype', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='VIDEO', max_length=10)),
                ('mediafile', models.FileField(null=True, upload_to=oplm.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mp3', 'jpeg', 'jpg'])])),
                ('remotelink', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('oplm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplm_media', to='oplm.Oplm')),
            ],
            options={
                'verbose_name': 'OPLM Media',
                'verbose_name_plural': 'OPLM Medias',
                'ordering': ('mediatype',),
            },
        ),
        migrations.CreateModel(
            name='OplmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OPLM Category',
                'verbose_name_plural': 'OPLM Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OplmBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog', to=settings.AUTH_USER_MODEL)),
                ('oplm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplm_blog', to='oplm.Oplm')),
            ],
            options={
                'verbose_name': 'OPLM Blog',
                'verbose_name_plural': 'OPLM Blogs',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='oplm',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplm_category', to='oplm.OplmCategory'),
        ),
        migrations.AddField(
            model_name='oplm',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oplm', to=settings.AUTH_USER_MODEL),
        ),
    ]
